### ISSUE TITLE
Conference Doctype: Issues

### ISSUE THREAD

**Issue by fossdot** [shridarpatil/indiafoss#1]
1. A field to capture the city name the made route like for home: indiafoss.net/`city_name`(lower_case)/`year`, schedule: indiafoss.net/`city_name`/`year`/schedule
3. An option to hide the schedule button from the hero section (since the schedule comes late after announcing the conference)
4. Option to add and hide a button (with custom label and link) in the hero section (for registration, call for proposal form for the speaker to submit or it could be used for `Join Now` action). 
5. Designation and Category field title has been swapped in the schedule **table**
![Screenshot - 2022-09-07T131606 930](https://user-images.githubusercontent.com/25725389/188820182-33c08981-f3a7-484f-8bd7-f71d41985c45.png)
6. Designation and Category field has been swapped in the schedule **web page**
![Screenshot - 2022-09-07T131918 263](https://user-images.githubusercontent.com/25725389/188821013-0f632a91-8fdd-4df5-983c-fadc998dc1f3.png)

**Comment by shridarpatil** [comment]
```
An option to hide the schedule button from the hero section (since the schedule comes late after announcing the conference)
```
The schedule button will show only after scheduling talks. Other issues are fixed.
