### ISSUE TITLE
Tasks

### ISSUE THREAD

**Issue by shridarpatil** [shridarpatil/indiafoss#2]
- [x]  Show the conference logo on top of the description 
- [x] Change primary navbar logo to FU logo
- [x] Talk Proposal doctype
- [x] Web form for talk Proposal
- [x] Conference date field change to the date picker
- [x] Schedule page breadcrumb change to the conference title
- [x] Navbar child table(label, links) limit to x
- [ ] notification emails for proposals (Accepted Rejected( email to user))

**Comment by fossdot** [comment]
@shridarpatil let's also work on the talk proposal notification.

**Comment by shridarpatil** [comment]
Can you provide me with the email templates?

**Comment by shridarpatil** [comment]
I have added this as notification.
