### ISSUE TITLE
Bugs/Notes

### ISSUE THREAD

**Issue by fossdot** [shridarpatil/indiafoss#3]
- [x] Start time in `Conference` doctype gets auto-clear after saving the document and message pop-ups: "`Mandatory fields required in Conference`:"
     `Start Time`
- [x] Remove the enable field in the `Conference Member` doctype, there's no use for it so it's a confusing UX.
- [x] Enable import is disabled in all doctype
- [x] `Orgnazie a Conference` link in the navbar is broken
- [x] Conference website link should be visible on the portal once we create/save the conference. Similiar to the website link on the web pages.

![Screenshot (1)](https://user-images.githubusercontent.com/25725389/202513903-d753aa3f-d65e-4f99-967c-48b36105be23.png)

- [x] Partner/Sponsor Table: We can show the `link` and `attach field` and the `name` field can be hidden (or the third field) as it is not compulsory.
- [x] ERROR: `TypeError: cannot unpack non-iterable NoneType object` when adding a talk from the admin desk if the `conference` field is not selected. Solution: Make the `conference` field mandatory.
- [x] Track is not visible seen in the schedule page
- [x] Talks should be in a column, currently, it's get added next in a row.

**Comment by shridarpatil** [comment]
fixed.
