### ISSUE TITLE
Fix the title of web page generated

### ISSUE THREAD

**Issue by karanmgandhi** [shridarpatil/indiafoss#4]
Title of he web page generated by Frappe Cloud comes out to be the Text entered in the **_City_** field. 
It must instead take title from the **_Title_** field. 

![image](https://user-images.githubusercontent.com/84027098/203511056-7d897322-a44f-4a34-8279-33483a290033.png)

![image](https://user-images.githubusercontent.com/84027098/203511101-d27b1451-5cdd-4e5b-9b1f-446d3d6e0669.png)

**Comment by shridarpatil** [comment]
Fixed

**Comment by fossdot** [comment]
Let's also add the subtitle field. It'll help us in SEO.
It should be: `Title - Subtitle`.

![Screenshot from 2022-11-28 11-57-37](https://user-images.githubusercontent.com/25725389/204208716-cca2cbab-a13d-459b-bea8-9a04232def3c.png)
