### ISSUE TITLE
Link Talks and Volunteers to the Conference doctype

### ISSUE THREAD

**Issue by fossdot** [shridarpatil/indiafoss#6]
All the talks and volunteers linked to a conference should be navigated through the conference doctype for ease of organizers.

Similar to this:
![Screenshot (11)](https://user-images.githubusercontent.com/25725389/204208184-c572bbfc-744d-424b-a78c-b83914a7514d.png)

**Comment by shridarpatil** [comment]
@wisharya We can only link talks, volunteers is a child table so we cannot link it. Also volunteer members we cant as it is not directly linked to conference doctype.

**Comment by shridarpatil** [comment]
![image](https://user-images.githubusercontent.com/11792643/204211574-ce610331-d6fe-4f4b-91f9-11afdabec8de.png)
Instead I can add a button which will land user to conference member list.

**Comment by fossdot** [comment]
Understood. Only linking the talks also works.

**Comment by shridarpatil** [comment]
No need to add a button?
